spring.application.name=ems

spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=lms_user
spring.datasource.password=lms_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true